### PR TITLE
update documentation according to internal requirements

### PR DESCRIPTION
**Pull request by spavlusieva**
Thanks for contributing!

Before submitting PRs for cx_Oracle you must have your signed *Oracle
Contributor Agreement* accepted.  See https://oca.opensource.oracle.com

If the problem solved is small, you may find it easier to open an Issue
describing the problem and its cause so we can create the fix.

The bottom of your commit message must have the following line using your name
and e-mail address as it appears in the OCA Signatories list.

```
Signed-off-by: Your Name <you@example.org>
```

This can be automatically added to pull requests by committing with:

```
git commit --signoff
````

### CODE REVIEW

**Comment by LesiaChaban** [comment]
Hello @anthony-tuininga and @cjbj Could you please review this PR and accept changes if it possible?

**Comment by cjbj** [comment]
I've created a similar request with the relevant changes on our internal repo.  This will get pushed back to GH on the next refresh.

**Comment by LesiaChaban** [comment]
@cjbj, will the changes requested by this closed PR be made to GH soon?

**Comment by cjbj** [comment]
They landed in https://github.com/oracle/python-cx_Oracle/commit/83774f95207e5ac0b01f2b4bb04056ddc54730aa

**Pull request closed without merging**
