### PR TITLE
Consolidate string handling in cxoTransform_toPython

### PR DESCRIPTION
**Pull request by alexhenrie**
There's no need to have the same code twice in this function.

### CODE REVIEW

**Comment by anthony-tuininga** [comment]
Thanks for noticing that the code is duplicated now that only Python 3 support is needed. We can only accept your contribution, however, if you sign the OCA. @cjbj can provide additional details if needed.

**Comment by cjbj** [comment]
@alexhenrie The OCA is [here](https://github.com/oracle/python-cx_Oracle/blob/master/CONTRIBUTING.md).  (Did this not get shown when you created the PR or do we need to tweak a template?)

**Comment by alexhenrie** [comment]
I have already signed the OCA. Is there another form I need to submit?

**Comment by cjbj** [comment]
Hi @alexhenrie thanks for doing that (even for this small change).  Has your OCA been accepted?  I don't immediately see your name on https://www.oracle.com/technetwork/community/oca-486395.html

Also, can you do the PR sign off `git commit --signoff` mention in the earlier link?

**Comment by alexhenrie** [comment]
It's in the H section, under "Alex Henrie", and I did include the Signed-off-by line in my commit message.

**Comment by alexhenrie** [comment]
I think maybe you missed it before because my OCA was originally for OpenJDK, but the page says that I don't need to sign a new one to contribute to other Oracle projects.

**Comment by cjbj** [comment]
@alexhenrie all is good. Thanks!

**Comment by anthony-tuininga** [comment]
Thanks!

**Comment by alexhenrie** [comment]
Thank you!

**Pull request merged**
