### PR TITLE
Fix build with PyPy 5.9.0-alpha0 in libpython mode

### PR DESCRIPTION
**Pull request by vnaydionov**
Proposed fix for #53 
blah blah

### CODE REVIEW

**Comment by cjbj** [comment]
Thanks for contributing.  Can you sign the OCA, see https://github.com/oracle/python-cx_Oracle/blob/master/CONTRIBUTING.md ?

**Comment by vnaydionov** [comment]
Hello, I've just signed and posted the OCA, also I've added the `Signed-off-by` clause to the commit message.

**Comment by vnaydionov** [comment]
Hi, Christopher!I had sent my signed/scanned agreement to oracle-ca_us [at] oracle [dot] comon Aug 21, but nothing happened.  23.07.2017, 02:13, "Christopher Jones" <notifications@github.com>:Thanks for contributing. Can you sign the OCA, see https://github.com/oracle/python-cx_Oracle/blob/master/CONTRIBUTING.md ?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- Best regards,Viacheslav Naydenov.

**Comment by cjbj** [comment]
@vnaydionov I'll chase up the team that monitors that mail queue and handles OCA approvals.

**Pull request merged**
